# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 04:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170811_0436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='demo_1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='demo_2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='demo_3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='demo_4',
        ),
        migrations.RemoveField(
            model_name='question',
            name='demo_5',
        ),
    ]
