# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20170811_0444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='demo_1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='demo_2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='demo_3',
        ),
        migrations.AddField(
            model_name='question',
            name='integer',
            field=models.IntegerField(blank=True, default='321', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='select',
            field=models.CharField(choices=[(0, 'Option 1'), (1, 'Option two'), (2, 'Option Teemo')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='textarea',
            field=models.TextField(default='Very long text, isnt it?', max_length=200),
        ),
    ]
