# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20170815_0447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='demo_4',
        ),
        migrations.RemoveField(
            model_name='question',
            name='demo_6',
        ),
        migrations.AddField(
            model_name='question',
            name='date_field',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='html_field',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='demo_5',
            field=models.TimeField(),
        ),
    ]
