# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20170815_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='select',
            field=models.CharField(choices=[('Option 1', 0), (1, 'Option two'), (2, 'Option Teemo')], max_length=1, null=True),
        ),
    ]
