# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20170816_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='select',
            field=models.CharField(choices=[('op1', 'Option 1'), ('op2', 'Option two'), ('op3', 'Option Teemo')], max_length=1, null=True),
        ),
    ]
